apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: email-pipeline

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: email-pipeline
    newName: email-pipeline
    newTag: latest
