apiVersion: v1
kind: Service
metadata:
  name: email-pipeline-ui
  namespace: email-pipeline
  labels:
    app.kubernetes.io/name: email-pipeline
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: email-pipeline
    app.kubernetes.io/component: ui
  ports:
    - port: 80
      targetPort: 8502
      protocol: TCP
      name: http
